eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8763
spring:
  application:
    name: gateway-service
  zipkin:
    base-url: http://localhost:8888
  sleuth:
      sampler:
        percentage: 1.0
zuul:
  routes:
    feign-consumer-hello:
      path: /user-api/**
      serviceId: user-service