server:
  port: 8763
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: zipkin-server
  zipkin:
    locator:
      discovery:
        enabled: true
    base-url: http://localhost:8888/
  sleuth:
    sampler:
      percentage: 1.0