server:
  port: 8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    metadata-map:
      user.name: admin
      user.password: 123456
spring:
  application:
    name: admin-server
boot:
  admin:
    routes:
      endpoints: evn, metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream
logging:
  file: "logs/boot-admin-sample.log"
security:
  user:
    password: 123456
    name: admin

