server:
  port: 8762
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eurake/
spring:
  cloud:
    config:
      server:
        git:
           uri: https://github.com/LiuHongJi821/SpringcloudConfig.git
           search-paths: resource
           username: LiuHongJi821
           password:
      label: master
  application:
    name: config-server-client-eurake