server:
   port: 8080
spring:
   #mysql数据源
   datasource:
      url: jdbc:mysql://58.49.89.72:3306/tx-manager?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: De@715832#
      min-idle: 5
      initial-size: 5
      max-active: 20
   redis:
      host: 114.55.237.147
      port: 6379
      password: jetsum123456
      # 连接超时时间（毫秒）
      timeout: 10000
      pool:
        # 连接池中的最大空闲连接
        max-idle: 80
        # 连接池中的最小空闲连接
        min-idle: 10
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
mybatis:
  mapper-locations: classpath*:/mybatis/*.xml